---
# tasks file for infra-book
- name: Configuration setting
  hosts: all
  become: yes
  tasks:
    - name: Checking for default paackages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - qemu-kvm
        - qemu
        - libvirt-bin
        - virt-manager
        - virt-viewer
        - virtinst
        - openvswitch-switch

    - name: Creating conf directory HypeTunnel directory locally
      file: path="/home/vm1/HypeTunnel/conf" state=directory
      hosts: hyp1

    - name: Creating HypeTunnel databaase file
      copy:
        content: ""
        dest: "{{ playbook_dir }}/HypeTunnel/HypeTunnel_database.txt"
        force: no
        hosts: hyp1
        owner: root
        mode: 0555

    - name: Creating an OVS bridge central_ovs
      openvswitch_bridge:
        bridge: central_ovs
        state: present

    - name: Create conf and  directory
      file: path="/home/vm1/HypeTunnel" state=directory

    - name: Create empty file for flows.txt
      copy:
        content: ""
        dest: "/home/vm1/HypeTunnel/flows.txt"
        force: no
        host: all
        owner: vm1
        mode: 0555

    - name: Creating VXLAN & GRE interface on central_ovs on hyp1
      shell: ovs-vsctl add-port central_ovs vxlan1 -- set interface vxlan1 type=vxlan options:local_ip=192.168.124.229 options:remote_ip=192.168.124.151
      hosts: hyp1

    - name: Creating GRE interface on central_ovs on hyp1
      shell: ovs-vsctl add-port central_ovs gre1 -- set interface gre1 type=gre options:remote_ip=192.168.124.151
      hosts: hyp1

    - name: Creating VXLAN interface on central_ovs on hyp2
      shell: ovs-vsctl add-port central_ovs vxlan1 -- set interface vxlan1 type=vxlan options:local_ip=192.168.124.151 options:remote_ip=192.168.124.229
      hosts: hyp2

    - name: Creating GRE interface on central_ovs on hyp2
      shell: ovs-vsctl add-port central_ovs -- gre1 set interface gre1 type=gre options:remote_ip=192.168.124.229
      hosts: hyp2
