---
# Playbook
- name: Check for libvirt packages and ovs
  apt: name="{{ item }}" state=present
  with_items:
    - qemu-kvm
    - libvirt-bin
    - virt-manager
    - virt-viewer
    - virtinst  
    - openvswitch-switch

- name: Create an OvS bridge sw1
  openvswitch_bridge:
    bridge: sw1
    state: present

- name: Create an OvS bridge sw2
  openvswitch_bridge:
    bridge: sw2
    state: present

- name: Create an OvS bridge sw3
  openvswitch_bridge:
    bridge: sw3
    state: present

- name: Create an OvS bridge sw4
  openvswitch_bridge:
    bridge: sw4
    state: present

- name: Define network internet
  virt_net:  
    command: define
    name: Internet
    xml: '{{ lookup("template", "internet.j2") }}'

- name: Define network l2
  virt_net:  
    command: define
    name: L2
    xml: '{{ lookup("template", "l2.j2") }}'

- name: Define network l3
  virt_net:  
    command: define
    name: L3
    xml: '{{ lookup("template", "l3.j2") }}'

- name: Define network other
  virt_net:  
    command: define
    name: Other
    xml: '{{ lookup("template", "other.j2") }}'

- name: Starting network internet
  virt_net:
      command: start
      name: Internet
      autostart: yes

- name: Starting network l2
  virt_net:
      command: start
      name: L2
      autostart: yes

- name: Starting network l3
  virt_net:
      command: start
      name: L3
      autostart: yes

- name: Starting network other
  virt_net:
      command: start
      name: Other
      autostart: yes

- name: Configuring L3 interfaces - SW1
  shell: ip addr add 192.168.140.1/24 dev sw1

- name: Configuring L3 interfaces - SW3
  shell: ip addr add 192.168.141.1/24 dev sw3

- name: Configuring L3 interfaces - SW4
  shell: ip addr add 192.168.142.1/24 dev sw4

- name: Starting SW1
  shell: ip link set sw1 up

- name: Starting SW2
  shell: ip link set sw2 up

- name: Starting SW3
  shell: ip link set sw3 up

- name: Starting SW4
  shell: ip link set sw4 up

- name: Configuring NAT on SW1
  shell: iptables -t nat -A POSTROUTING -o sw1 -j MASQUERADE
